# Site
name: 'mzQC'
title: 'mzQC website'
minima:
  skin: dark
#remote_theme: jekyll/minima
header_pages:
  - about.md
  - validator.html

author:
  name: HUPO-PSI QC working group
  email: "psidev-qc-dev@lists.sourceforge.net"

# Exclude metadata and development stuff
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
show_excerpts: true
minima:
  social_links:
    github:  jekyll

# Build settings
theme: minima

#plugins:
# - jekyll-feed
# - jekyll-seo-tag
